[package]
name = "sond-bevy-particles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9.0-dev", default-features = false }
rand = "0.8.5"